export const FiltersList = {
  businesses: [
    "Comercios",
    "Restaurantes",
    "Tecnología",
    "Ferreterías",
    "Peluquerías",
    "Servicios",
    "Otros"
  ],
  offers: {
    ['Comercios']: [
      "Frutas y Verduras",
      "Pollo y Huevos",
      "Carnes",
      "Pescados y mariscos",
      "Lacteos",
      "Desayuno",
      "Embutidos y fiambres",
      "Abarrotes",
      "Panes y biscochos",
      "Aguas y bebidas gaseosas",
      "Cerveza, vinos y licores",
      "Limpieza y aseo",
      "Hogar y Bazar",
      "Limpieza de ropa y calzado",
      "Limpieza del hogar",
      "Higiene y cuidado del cabello",
      "Higiene y cuidado personal",
      "Belleza y Maquillaje",
      "Alimento de Mascotas",
      "Juguetes y regalos",
      "Artículos para niños y bebes",
      "Útiles escolares y de oficina",
      "Gas"
    ],
    ['Restaurantes']: [
      "Menú",
      "Hamburguesas",
      "Pizza",
      "Pollo a la Brasa",
      "Cebiche",
      "Tortas",
      "Platos a la Carta",
      "Postres",
      "Anticuchos",
      "Sandwich",
      "Bebidas Gaseosas"
    ],
    ['Tecnología']: [
      "Laptops",
      "Computadoras",
      "Impresoras",
      "Monitores",
      "Accesorios para computadoras",
      "Componentes gamers",
      "Videojuegos",
      "Consolas",
      "Mandos",
      "Routers y conexión inalámbrica",
      "Streaming",
      "Asistentes de voz",
      "Aspiradoras robot",
      "Seguridad inteligente",
      "Equipos de sonido",
      "Audífonos",
      "Parlantes",
      "Accesorios de audio",
      "Cámaras semiprofesionales",
      "Cámaras profesionales",
      "Accesorios para cámaras",
      "Drones",
    ],
    ['Ferreterías']: [
      "Herramientas y accesorios",
      "Artículos de construcción",
      "Ladrillos y arenas",
      "Cementos",
      "Pinturas y acabados",
      "Lamparas y colgantes",
      "Tableros aglomerados",
      "Cables y alambres eléctricos",
      "Interruptores y tomacorrientes",
      "Tubos eléctricos y de gasfitería",
      "Tableros y llaves termomagnéticas",
      "Productos de fijación",
      "Accesorios de seguridad",
      "Accesorios sanitarios y gasfitería",
      "Tanques de agua y accesorios",
      "Accesorios para pintar",
      "Productos químicos y limpiadores",
      "Focos e iluminación interior",
      "Iluminación exterior"
    ],
    ['Peluquerías']: [
      "Corte para caballeros",
      "Corte para damas",
      "Pintado del cabello",
      "Peinados y laseados",
      "Manicure",
      "Pedicure",
      "Barbería",
      "Cortes con diseño",
      "Cortes para niños"
    ],
    ['Servicios']: [
      "Lavanderías",
      "Lavadero de autos",
      "Agentes multibanco",
      "Casas de cambio",
      "Gasfitería",
      "Carpintería",
      "Fabricación de modulares y melamine",
      "Electrónica",
      "Electricista",
      "Mantenimiento y pintura",
      "Albañilería y construcción"
    ],
    ['Otros']: [
      "Farmacias y boticas",
      "Panaderías y pastelerías",
      "Librerías",
      "Confecciones Textiles",
      "Florerías",
      "Vidrierías",
      "Regalos y novedades",
      "Lubricantes",
      "Repuestos para autos",
      "Lavadero de autos"
    ]
  },
  districts: [
    'Chimbote',
    'Nuevo Chimbote'
  ],
  zones: {
    ['Chimbote']: [
      "La Caleta - Bolivar Alto",
      "El Progreso - 2 de Mayo",
      "El Carmen - La Union",
      "Esperanza Alta - San Pedro",
      "Laderas - Los Pinos",
      "Miramar Bajo - Alto Peru",
      "Miraflores Bajo - San Juan",
      "Florida baja - El Trapecio"
    ],
    ['Nuevo Chimbote']: [
      "Villa Maria - 1ro Mayo",
      "PPAO - 3 de Octubre",
      "Buenos Aires - Casuarinas",
      "Mariscal Luzuriaga - Santa Rosa",
      "Santa Cristina - Villa Agraria",
      "Jose Carlos Mariategui - Bruces",
      "Los Alamos - Nicolas Garatea",
      "Las Poncianas - San Luis"
    ]
  }
}
